
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CarRental
{

using System;
    using System.Collections.Generic;
    
public partial class Branch
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Branch()
    {

        this.Cars = new HashSet<Car>();

    }


    public int BranchID { get; set; }

    public string BranchName { get; set; }

    public string BranchAddress { get; set; }

    public double Geodata { get; set; }



    public virtual Branch Branches1 { get; set; }

    public virtual Branch Branch1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Car> Cars { get; set; }

}

}
